version: '3'
services:
  validator-alice:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e5855c5
    ports:
      - '30333:30333'
      - '9944:9944'
      - '9933:9933'
    volumes:
      - ./:/data
    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/validator_alice_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry

  validator-bob:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e5855c5
    ports:
      - '30335:30335'
      - '9922:9922'
      - '9911:9911'
    volumes:
       - ./:/data

    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/validator_bob_data
      - --port=30335
      - --ws-port=9922
      - --rpc-port=9911
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry

  validator-charlie:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e5855c5
    ports:
      - '30336:30336'
      - '8822:8822'
      - '8811:8811'
    volumes:
        - ./:/data

    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/validator_charlie_data
      - --port=30336
      - --ws-port=8822
      - --rpc-port=8811
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --charlie
      - --no-prometheus
      - --no-telemetry

  validator-dave:
    image: joshyorndorff/cumulus-workshop-polkadot:sha-e5855c5
    ports:
      - '30337:30337'
      - '8844:8844'
      - '8833:8833'
    volumes:
        - ./:/data

    command:
      - --chain=/data/dex_raw.json
      - --base-path=/data/validator_dave_data
      - --port=30337
      - --ws-port=8844
      - --rpc-port=8833
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --dave
      - --no-prometheus
      - --no-telemetry